version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: hvt-lamda-dynamodb
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - '8000:8000'
    networks:
      - localdev

networks:
  localdev:
    name: hvt-lambda-network
    driver: bridge
