name: Feature Request 
description: Request a new feature and enhancement
title: "[Feature Request]: "
labels: ["feature"] 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: What would you like to see implemented?
      placeholder: Please provide as much information and background as you can
    validations:
      required: true
  - type: textarea
    id: alternative-information
    attributes:
      label: Are you currently using a workaround / alternative solution instead?
      placeholder: Please provide as much information and background as you can
    validations:
      required: true